### ISSUE TITLE
HTTP 500 error in 3 versions of moodle

### ISSUE THREAD

**Issue by richardbitgood** [jmvedrine/moodle-qformat_qtitwo#1]
Hi Jean-Michel,

I have tried installing on Moodle 2.7, Moodle 3.0 and Moodle 3.1 on two different servers and the install goes fine with no errors, but when I go to export a category, I get a blank screen and a HTTP 500 error.

Have you used this recently at all or ever run into that issue?

**Comment by jmvedrine** [comment]
Hello Richard,
I am sorry but I am now retired and I stopped using Moodle in 2016, I also stopped all programming work. I will add a comment to the readme.

**Comment by danmarsden** [comment]
just filed a pull request that fixes the HTTP 500 error but haven't performed a full review. If someone wants to pick this up now that Jean-Michel has retired and use this a production environment they should definitely replace the smarty version as it is known to have some security issues.

**Comment by jmvedrine** [comment]
I committed Dan Marsden's changes. But please note this is not maintained anymore and as Dan said if someone wants to use it he should definitely upgrade the smarty version (which will need to upgrade all the templates too)
